function myMeshResult(xdata1, ydata1, zdata1,inXtitle,inYtitle,inZtitle)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 10-Jul-2014 15:06:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'ZScale','log','ZMinorTick','on',...
    'ZMinorGrid','on');
view(axes1,[-121.5 28]);
grid(axes1,'on');
hold(axes1,'all');

% Create mesh
mesh(xdata1,ydata1,zdata1,'Parent',axes1,'DisplayName',inZtitle);
% Create zlabel
zlabel(inZtitle,'Interpreter','none');
ylabel(inYtitle,'Interpreter','none');
xlabel(inXtitle,'Interpreter','none');

