- {A1_HLM: 500, A2_HLM: 30, CS_ACTIVE: '4', CS_ANGLEXY: '0.0', CS_ANGLEXZ: '45.0', CS_GEARTX: '360000.0',
  J1_HLM: 15000.0, J2_HLM: 100, T_IN_LLM: '0.005',
  
  EPICS_PREFIX : 'SR05ID01FST02:RSCN'
  
  }

- {A1_HLM: 56, A2_HLM: 6.96, CS_ACTIVE: '4', CS_ANGLEXY: '0.0', CS_ANGLEXZ: '45.0', CS_GEARTX: '360000.0',
  J1_HLM: 15000.0, J2_HLM: 100, T_IN_LLM: '0.005',
  
  EPICS_PREFIX : 'SR05ID01FST02:RSCN'
  
  }
